### ISSUE TITLE
automl / launch distributed training job

### ISSUE THREAD

**Issue by gionatamettifogo** [analitico/analitico-automl#23]

**Comment by danielebriggi** [comment]
Tried to implement distribution with `MultiworkerMirroredStrategy` but it doesn't work due to exception on `wrong output tensor dimension` (probably a bug). Thus we used the strategy `ParameterServer`.

#### Test on Kubernetes on
- a octa core (16 cores) server
- 100k steps
- S24 Payment Time dataset

#### Results
- 1 core / 1 replica - loss: 8800, time: 46m
- 4 cores / 1 replica - loss: 8600, time: 8m
- all cores (~16 cores) / 1 replica - loss: 7753, time: 2m

- 1 core / 4 replicas - loss: 800, time: 27m
- 1 core / 8 replicas - loss: N/A, time: >21m 

### Conclusion
The distributed strategy on a tfjob in multiple replicas saves ~40% of the train time. The time spent to sync the replicas impacts a lot plus it decrease with the number of workers (it may be caused by steps too fast to process but a very high latency time to retrieve rows).

In the end we go for distribution on multiple cores on the single machine.
