### ISSUE TITLE
Add support for RNNRegressor

### ISSUE THREAD

**Issue by gionatamettifogo** [analitico/analitico-automl#4]
Initial test case that we are trying to get to work:
https://github.com/analitico/analitico-automl/commit/f917ed2eadf4f2f458ab754390fce0d3115d7155
automl_test.py/test_timeseries_with_waves

First:
- [ ] see if csv generator can be made to split data chronologically:
- [ ] add tf.estimator.RNNRegressor to estimators.py 
- [ ] add metrics that may make sense for a time series
- [ ] check that data is split correctly, training works, results make sense
- [ ] check that data is split correctly, training works, results make sense

Then:
- [ ] find a simple but more realistic dataset, try, test
- [ ] find a more complete dataset, try, test

Assumptions:
- For now we assume that data is sourced in the correct chronological order
- For now we assume that the column used for timestamp is "yt" (I will get this parametrically from automl_conf)

**Comment by fmardero** [comment]
Some first notes:
- Tensorflow does not implement yet, not even as experimental, the RNNRegressor. We need to use the RNNEstimator with regression head as pointed [here](https://www.tensorflow.org/api_docs/python/tf/estimator/experimental/RNNEstimator).
- The RNNEstimator requires [`SequenceFeatures`](https://www.tensorflow.org/api_docs/python/tf/keras/experimental/SequenceFeatures) as input. The transform component, will be impacted by this requirement. For example when the time column is used (from `automl_config`) all of the numeric features must be transformed using [`sequence_numeric_column`](https://www.tensorflow.org/api_docs/python/tf/feature_column/sequence_numeric_column) instead of the usual `numeric_column` function.
- To distinguish the sequential features from the "common" ones another suffix needs to be provided to their name.

Due to this complexity, first tests will be developed using only the `time_column` (`xt`) and the `target_column` (`yt`).

**Comment by gionatamettifogo** [comment]
You can run the time series code in Debug and Run > Python One Test
by changing launch.json -> Python One Test -> AutomlTest.test_regression_with_identity_integers

Test code in automl_test/test_timeseries_with_waves

I added:

- components/transform/transform.py/preprocessing_fn
   generates XF_SEQUENCE_NUMERIC however training later complains that this isn't a sparse tensor

- components/trainer/estimators.py/_get_estimator_features
  creates sequence features for use by RNNs

- components/trainer/estimator.py/build_estimator
   creates tf.estimator.experimental.RNNEstimator

the trainer complains on the sequence feature not being based on sparse tensor
0129 10:28:17.960166 140029805967104 estimators.py:607] in converted code:
    relative to /opt/venv/lib/python3.6/site-packages:

    tensorflow_estimator/python/estimator/canned/rnn.py:204 call  *
        sequence_input, sequence_length = self._sequence_features_layer(inputs)
    tensorflow_core/python/keras/engine/base_layer.py:847 __call__
        outputs = call_fn(cast_inputs, *args, **kwargs)
    tensorflow_core/python/feature_column/sequence_feature_column.py:140 call
        transformation_cache, self._state_manager)
    tensorflow_core/python/feature_column/sequence_feature_column.py:555 get_sequence_dense_tensor
        sp_tensor, default_value=self.default_value)
    tensorflow_core/python/ops/sparse_ops.py:1472 sparse_tensor_to_dense
        sp_input = _convert_to_sparse_tensor(sp_input)
    tensorflow_core/python/ops/sparse_ops.py:68 _convert_to_sparse_tensor
        raise TypeError("Input must be a SparseTensor.")

    TypeError: Input must be a SparseTensor.

**Comment by gionatamettifogo** [comment]
Will not implement time series but will work on regular classifier/regressor that have a time column, used to split train/test chronologically #6 and also work on augmenting dates #30
